# Service - LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: showhostname
spec:
  selector:
    app: showhostname
  type: LoadBalancer
  ports:
  - nodePort: 31000
    port: 80
    targetPort: 8080